# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'WasteManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Analytics'

	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
 	pod 'Firebase/Database'

	# Optionally, include the Swift extensions if you're using Swift.
	pod 'FirebaseFirestoreSwift'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'Firebase/Functions'
	pod 'IQKeyboardManagerSwift'
	pod 'Kingfisher', '~> 4.0' 

  # Pods for WasteManagement
target 'WasteManagementTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'

  # Pods for WasteManagementTests


  end

end
